name: Laravel CI Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup PHP Environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, dom, curl, pdo, pdo_mysql, bcmath, sqlite, pdo_sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: pcov

      # 3. Cache Composer Dependencies
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 4. Install Dependencies
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-interaction

      # 5. Prepare Laravel Environment for Testing
      - name: Prepare Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      # 6. Run Database Migrations
      - name: Run Database Migrations
        run: php artisan migrate --force # Use --force for non-interactive environments

      # 7. Run Tests
      - name: Execute tests (PHPUnit)
        run: php artisan test --coverage --min=80.3
